---
title: Week 4
subtitle: Data-types 
format: stat198slides-revealjs
---

# Introduction

This is a sample deck for DataViz DeCal Slides. The features include:

1. Title slide with background image.
2. A bunch of yaml defaults.
3. Clickable logo in lower right that links to the previous page.
4. No logo or slide number on title slide.
5. Custom `:::poll` div for poll questions.
6. A [countdown timer](https://github.com/gadenbuie/countdown/tree/main/quarto) accessible by adding

   `{{< countdown "01:30" >}}`
   
   on a new line.


# Agenda

- Understand different types of variables and how they influence chart selection.  
- Understand how different purposes or ana;ytical tasks influence chart selection.
- Learn how to match data structures to appropriate visial encodings
- Acknowledge esistence of graphics all over the data analysis cycle, and how graphics can be broadly divided into "Exploration" and "Communication".

# Discussion of Assigned Reading 

- Reading: The Persistent Grip of Social Class on College Admissions 
- Warm up question: 
- Follow up reading questions:
- In what ways do the graphs differ?

::: poll
What is your favorite color?

A. Red  
B. Green  
C. Blue  
:::

{{< countdown "01:30" >}}


## Code Example

Here’s an example of code and output using **ggplot2** in R.

```{r}
#| output-location: column-fragment
library(ggplot2)

ggplot(mtcars, aes(x = wt, y = mpg, color = factor(cyl))) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    title = "Miles per Gallon vs. Weight",
    color = "Cylinders"
  )
```

## Two Columns {.smaller}

::: columns
::: column

Explanation

Columns are great for mixing code, plots, and text.\

- Left and right content\

- Works well for comparisons\

- Helps structure visual walkthroughs\
:::

::: {.column .fragment}
Example plot
:::
:::

# Wrap-Up

### Quarto slides make teaching reproducible

::: poll adds interactivity

{{< countdown >}} adds time control

YAML controls defaults (logos, themes, layout)
