---
title: "5) Color 1 - Quiz and RBG Model"
---

## This Week: 

In this week, we'll start talking about color, specifically about the RGB color models, and you will work on an in-class activity (due at the end of the day today at 11:59PM).

We will learn about the RGB color model and its cubic geometric representation, which has very interesting mathematical properties


More important, the main practical tools that emanate from this color theory are the __color-picker__ devices. 


<br>


### 🎯 Objectives

At the end of this unit you will be able to:

- Explain the RBG theory of color vision.

- Describe what color models are typically used in color-picker tools.

- Explain the color wheel.

- Use the RBG color picker tool in R.


<br>


### 🌠 Slides

Find today's slides [here.](slides.html)


### 💻 Code

Found on BCourses under Week 5

<br>


### 📖 Assignment

__Reading__: _Age of US Presidents (Pew Research Center)_

<a href="https://www.pewresearch.org/short-reads/2023/10/10/most-us-presidents-have-been-in-their-50s-at-inauguration/" target="_blank">https://www.pewresearch.org/short-reads/2023/10/10/most-us-presidents-have-been-in-their-50s-at-inauguration/</a>

__Homework__: Today's in-class activity is due tonight, 3/10 at 11:59pm. You can find the assignment and turn in your work on BCourses.
