---
title:  Week 2
subtitle:  Introduction to the Grammar of Graphics
format: stat198slides-revealjs
---

# Learning Goals

-   Understand the theoretical framework of the Grammar of Graphics
-   Break down key components of a graphic: data, aesthetics, geoms, stats, scales, facets, themes
-   Learn how ggplot2 implements this grammar in practice

# Agenda

-   Discussion of Assigned Reading\
-   Sketching Activity\
-   Lecture\
-   Code Example\
-   Wrap-up\

# Discussion

**Reading:** [The Age That Women Have Babies](https://www.nytimes.com/interactive/2018/08/04/upshot/up-birth-age-gap.html)

Get into groups of 2-3 people and discuss the following questions: 
- What do you think of the use of color 
-

# Sketching Activity

# Leture
## What is grammar in graphics?


# Code Example

Here’s an example of code and output using **ggplot2** in R.

```{r}
#| output-location: column-fragment
library(ggplot2)

ggplot(mtcars, aes(x = wt, y = mpg, color = factor(cyl))) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    title = "Miles per Gallon vs. Weight",
    color = "Cylinders"
  )
```

## Two Columns {.smaller}

::::: columns
::: column
Explanation

Columns are great for mixing code, plots, and text.\

-   Left and right content\

-   Works well for comparisons\

-   Helps structure visual walkthroughs\
:::

::: {.column .fragment}
Example plot
:::
:::::

# Wrap-Up

### Quarto slides make teaching reproducible

::: poll adds interactivity

{{< countdown >}} adds time control

YAML controls defaults (logos, themes, layout)
