---
title: "HW 4: Data Visualization"
subtitle: "Stat 198, Spring 2026"
fontsize: 12pt
urlcolor: blue
output: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


## Screen Time's Barchart Replication

The following table contains the data of the barchart (units: minutes).

|      Days | Social | Entertainment | Creativity | Other |
|:----------|:-------|:--------------|:-----------|:------|
|    Sunday |    107 |            29 |          1 |   101 |
|    Monday |    100 |            22 |          3 |    22 |
|   Tuesday |     46 |            32 |          8 |    69 |
| Wednesday |     88 |            14 |          1 |    44 |
|  Thursday |    117 |             0 |          1 |    72 |
|    Friday |     69 |             1 |          1 |    39 |
|  Saturday |     98 |             0 |          9 |    46 |

<br>

```{r}
# 1) Here's one way to obtain the input data table

# input vectors
days = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
social = c(107, 100, 46, 88, 117, 69, 98)
entertainment = c(29, 22, 32, 14, 0, 1, 0)
creativity = c(1, 3, 8, 1, 1, 1, 9)
other = c(101, 22, 69, 44, 72, 39, 46)

# assemble data frame
tbl <- data.frame(
  'Day' = days,
  'Social' = social,
  'Entertainment' = entertainment,
  'Creativity' = creativity,
  'Other' = other
)

# reshape into long (tall) format for ggplot convenience
tbl <- pivot_longer(
  data = tbl,            # table to be reshaped
  cols = Social:Other,   # variables to be "stacked" together
  names_to = "Category", # column-name of stacked variables
  values_to = "Time")    # column-name of stacked values

# convert time from minutes to hours
tbl <- mutate(tbl, Time = Time / 60)

head(tbl)
```

<br>

```{r eval = FALSE}
# another way to create a data tabe in "long" (tall) format
# for ggplot() convenience

Day <- rep(x = c("Sunday", 
                 "Monday", 
                 "Tuesday", 
                 "Wednesday", 
                 "Thursday",
                 "Friday", 
                 "Saturday"), 
           each = 4)

Category <- rep(x = c("Social", "Entertainment", "Creativity", "Other"), times = 7)

Time <- c(107, 29, 1, 101,
          100, 22, 3, 22,
          46, 32, 8, 69,
          88, 14, 1, 44,
          117, 0, 1, 72,
          69, 1, 1, 39,
          98, 0, 9, 46) / 60

tbl <- data.frame(Day, Category, Time)
```

<br>

```{r}
# 2) Total time per day
# (to be used later to get average time)
dat_total_time = tbl %>% 
  group_by(Day) %>%
  summarise(total_time = sum(Time)) %>%
  ungroup()

dat_total_time
```

<br>

```{r}
# 3) Barchart
# (code based on Angel Alcala's submission)

# color palette
orange1 = "#E59400"
light_gray1 = "#939393"
gray1 = "#4C4C4C"
blue1 = "#2D89E5"
light_blue1 = "#96C4F2"
green1 = "#00B300"


# barchart
ggplot(
  data = tbl, 
  aes(x = Day, 
      y = Time, 
      fill = factor(Category, levels = c("Other", "Creativity", "Entertainment","Social")))) +
  geom_bar(width = 0.6, position = "stack", stat = "identity") +
  # customizing scale elements
  scale_x_discrete(limits = days, labels = c("S", "M", "T", "W", "T", "F", "S")) +
  scale_y_continuous(labels = c("0", " ", " ", " ", "4h"), position = "right") + 
  geom_hline(yintercept = mean(dat_total_time$total_time),
             color = green1,
             linetype = "dashed") +
  scale_fill_manual(values = c(gray1, 
                               orange1,
                               light_blue1,
                               blue1)) +
  # theme elements
  theme(panel.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = gray1),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(linetype = "dashed"),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        plot.background = element_rect(fill = "black"),
        legend.position = "none",
        plot.margin = unit(c(2.4,.7,2.4,.4), "cm"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  # annotations
  annotate("text", x = 1.3, y = 5.25, label = "Daily Average", size = 5.5, color = light_gray1) +
  annotate("text", x = 1.3, y = 4.6, label = "2h 38m", size = 10.5, color = "white") +
  annotate("text", x = 6.7, y = 4.5, label = "28% from last week", size = 5.5, color = light_gray1) + 
  annotate("text", x = 7.85, y = 2.75, label = "avg", size = 5, color = green1) +
  annotate("text", x = .96, y = -1.2, label = "Social", size = 6, color = blue1) +
  annotate("text", x = 4, y = -1.2, label = "Entertainment", size = 6, color = light_blue1) + 
  annotate("text", x = 7.25, y = -1.2, label = "Creativity", size = 6, color = orange1) + 
  annotate("text", x = .96, y = -1.7, label = "10h 21m", size = 6, color = "white") +
  annotate("text", x = 4, y = -1.7, label = "1h 10m", size = 6, color = "white") + 
  annotate("text", x = 7.25, y = -1.7, label = "24m", size = 6, color = "white") + 
  coord_cartesian(xlim = c(1,7), ylim = c(0,4), clip = "off")
```