---
title: "8) Spatial Data 1"
---

## This Week: 

In this week, we'll get a further introduction to design considerations in data viz and you will turn in HW5 (Friday 11:59pm).

This class condenses some of the core data visualization principles proposed by the main gurus (Colin Ware, Stephen Few, Edward Tufte, Alberto Cairo, etc). In no particular order, we present the principles, providing examples for each of them. Overall, today’s slides are a bunch of “Do’s and Don’ts”. Likewise, we briefly introduce the profiles of the gurus behind the core principles, and the associated literature (just for reference purposes for the interested reader).


<br>


### 🎯 Objectives

At the end of this unit you will be able to:

- Understand the core data visualization principles and know how they originated
- Analyze how visualizations can mislead or “lie” by examining the lie factor
- Redesign a cluttered chart into a clear and efficient one.


<br>


### 🌠 Slides

Find today's slides [here.](slides.html)


### 💻 Code

TBA


<br>


### 📖 Assignment

__Reading__: No reading assigned! 

__Homework__: No HW assigned! Study for Quiz 2. 
